### ISSUE TITLE
inputTextController

### ISSUE THREAD

**Issue by ChandAbdullah** [koukibadr/Blurry#19]
There is an issue in the inputTextController.
How can I get the inputTextController.text on confirm button?

`

> showInputDialogAlert(
>   BuildContext context,
>   String header,
>   String message,
>   String confirmText,
>   String inputLable,
>   TextEditingController inputTextController,
>   Function onConfirmClick,
> ) {
>   Blurry dialogAlert = Blurry.input(
>     title: header,
>     textInputType: TextInputType.multiline,
>     defaultTheme: DEFAULT_THEMES.error,
>     description: message,
>     inputLabel: inputLable,
>     inputTextController: inputTextController,
>     confirmButtonText: confirmText,
>     onConfirmButtonPressed: () {
>       print(inputTextController.text);
>     },
>   );
>   dialogAlert.show(context);
> }

`

**I'm printing the `inputTextcontroller.text` but it shows the empty value**

**Comment by ChandAbdullah** [comment]
@koukibadr did you know how to solve this bug?

**Comment by koukibadr** [comment]
@ChandAbdullah I will work on it today I will let you know once it fixed

**Comment by ChandAbdullah** [comment]
@koukibadr thanks and waiting for your response...

**Comment by koukibadr** [comment]
@ChandAbdullah the issue is fixed you can refer to the github repo in your project's pubspec.yaml file to get the recent modifications otherwise the bug fix will be available in the next version

**Comment by koukibadr** [comment]
@ChandAbdullah the bug fix is now available in the version 1.4.1 check it out 
[https://pub.dev/packages/blurry](https://pub.dev/packages/blurry)

**Comment by ChandAbdullah** [comment]
@koukibadr now how can i get the value of inputTextController?

**Comment by ChandAbdullah** [comment]
@koukibadr I have a new **suggestion** for you to do this input dialog more catchable.
You have to implement the **form validation** on accepting click with a new optional attribute "**validationOnConfirm**".
and also you can add animation in the input field on accept click if the field is empty.
Think about my opinion.

**Comment by koukibadr** [comment]
> @koukibadr I have a new **suggestion** for you to do this input dialog more catchable. You have to implement the **form validation** on accepting click with a new optional attribute "**validationOnConfirm**". and also you can add animation in the input field on accept click if the field is empty. Think about my opinion.

thanks for the idea I will implement it in the next version

**Comment by ChandAbdullah** [comment]
My pleasure ;)
