### ISSUE TITLE
[Question] How to dismiss the modal without cancel button

### ISSUE THREAD

**Issue by khuccui2002** [koukibadr/Blurry#24]
Hello @koukibadr ,
I'm using Blurry and I had a problem that I can not close the modal without cancel button. I read the document and I can not find event to close the modal. Could you please show me how to close the modal without cancel button.
Thanks!

**Comment by khuccui2002** [comment]
I found the way to close the modal
Navigator.pop(context).
So I close ticket. 
Thanks!

**Comment by koukibadr** [comment]
Happy to  help if you have anything I can help you with
